# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '6_jaut.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 185)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(255, 212, 253);\n"
"gridline-color: rgb(255, 137, 246);\n"
"selection-background-color: rgb(216, 145, 222);\n"
"selection-color: rgb(177, 116, 179);\n"
"border-color: rgb(120, 68, 113);\n"
"alternate-background-color: rgb(152, 92, 141);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pogaTalak = QtWidgets.QPushButton(self.centralwidget)
        self.pogaTalak.setGeometry(QtCore.QRect(270, 140, 31, 21))
        self.pogaTalak.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pogaTalak.setStyleSheet("background-color: rgb(189, 126, 189);\n"
"font: 8pt \"Consolas\";")
        self.pogaTalak.setObjectName("pogaTalak")
        self.teksts = QtWidgets.QLabel(self.centralwidget)
        self.teksts.setGeometry(QtCore.QRect(10, 10, 301, 51))
        self.teksts.setStyleSheet("font: 14pt \"Consolas\";\n"
"border-top-color: rgb(156, 103, 167);")
        self.teksts.setObjectName("teksts")
        self.jaut6_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.jaut6_1.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.jaut6_1.setStyleSheet("font: 8pt \"Consolas\";")
        self.jaut6_1.setTristate(False)
        self.jaut6_1.setObjectName("jaut6_1")
        self.jaut6_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.jaut6_2.setGeometry(QtCore.QRect(10, 130, 81, 21))
        self.jaut6_2.setStyleSheet("font: 8pt \"Consolas\";")
        self.jaut6_2.setObjectName("jaut6_2")
        self.jaut6_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.jaut6_3.setGeometry(QtCore.QRect(110, 80, 71, 21))
        self.jaut6_3.setStyleSheet("font: 8pt \"Consolas\";")
        self.jaut6_3.setTristate(False)
        self.jaut6_3.setObjectName("jaut6_3")
        self.jaut6_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.jaut6_4.setGeometry(QtCore.QRect(110, 130, 81, 21))
        self.jaut6_4.setStyleSheet("font: 8pt \"Consolas\";")
        self.jaut6_4.setTristate(False)
        self.jaut6_4.setObjectName("jaut6_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Tests"))
        self.pogaTalak.setText(_translate("MainWindow", "->"))
        self.teksts.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Kuri no sekojošajiem operatoriem</p><p align=\"center\">tiek izmantoti loģiskai operācijai?</p></body></html>"))
        self.jaut6_1.setText(_translate("MainWindow", "and"))
        self.jaut6_2.setText(_translate("MainWindow", "&&"))
        self.jaut6_3.setText(_translate("MainWindow", "or"))
        self.jaut6_4.setText(_translate("MainWindow", "not"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
