# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beiguEkrans.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 185)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(255, 212, 253);\n"
"gridline-color: rgb(255, 137, 246);\n"
"selection-background-color: rgb(216, 145, 222);\n"
"selection-color: rgb(177, 116, 179);\n"
"border-color: rgb(120, 68, 113);\n"
"alternate-background-color: rgb(152, 92, 141);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 301, 91))
        self.label.setStyleSheet("font: 20pt \"Consolas\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 141, 16))
        self.label_2.setStyleSheet("font: 10pt \"Consolas\";")
        self.label_2.setObjectName("label_2")
        self.mvelReiz = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.mvelReiz.setGeometry(QtCore.QRect(170, 130, 116, 17))
        self.mvelReiz.setStyleSheet("font: 8pt \"Consolas\";\n"
"background-color: rgb(189, 126, 189);")
        self.mvelReiz.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.mvelReiz.setObjectName("mvelReiz")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Tests"))
        self.label.setText(_translate("MainWindow", "Tavs rezultats:"))
        self.label_2.setText(_translate("MainWindow", "Gribi meģināt vel reiz?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
