# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ievadiVardu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 185)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        MainWindow.setStyleSheet("background-color: rgb(255, 212, 253);\n"
"gridline-color: rgb(255, 137, 246);\n"
"selection-background-color: rgb(216, 145, 222);\n"
"selection-color: rgb(177, 116, 179);\n"
"border-color: rgb(120, 68, 113);\n"
"alternate-background-color: rgb(152, 92, 141);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saktTests = QtWidgets.QPushButton(self.centralwidget)
        self.saktTests.setGeometry(QtCore.QRect(90, 130, 131, 21))
        self.saktTests.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.saktTests.setStyleSheet("background-color: rgb(189, 126, 189);\n"
"font: 8pt \"Consolas\";")
        self.saktTests.setObjectName("saktTests")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 70, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 151, 20))
        self.label.setStyleSheet("font: 20pt \"Consolas\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Tests"))
        self.saktTests.setText(_translate("MainWindow", "Sākt testēšanu"))
        self.label.setText(_translate("MainWindow", "Ievadi vārdu:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
